language: cpp
cache:
  - apt
compiler:
  - clang
  - gcc
before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y lib32gcc1
  - sudo apt-get install -y libc6-i386
  - sudo apt-get install -y lib32z1-dev
  - sudo apt-get install -y lib32stdc++6
  - sudo apt-get install -y g++-multilib
  - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - unzip gtest-1.7.0.zip && cd gtest-1.7.0 && g++ src/gtest-all.cc -I. -Iinclude -c && g++ src/gtest_main.cc -I. -Iinclude -c && ar -rv libgtest.a gtest-all.o && ar -rv libgtest_main.a gtest_main.o && mv *.a /usr/local/lib && g++ -m32 src/gtest-all.cc -I. -Iinclude -c && g++ -m32 src/gtest_main.cc -I. -Iinclude -c && ar -rv libgtest.a gtest-all.o && ar -rv libgtest_main.a gtest_main.o && mkdir /usr/local/lib32 && mv *.a /usr/local/lib32
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
# We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
env:
  - ACTION="ci/build_autotools.sh" VERSION="cpp11" ARCH="64"
  - ACTION="ci/build_autotools.sh" VERSION="cpp11" ARCH="32"
  - ACTION="ci/build_autotools.sh" VERSION="cpp03" ARCH="64"
  - ACTION="ci/build_autotools.sh" VERSION="cpp03" ARCH="32"
  - ACTION="ci/build_cmake.sh"     VERSION="cpp11" ARCH="64"
  - ACTION="ci/build_cmake.sh"     VERSION="cpp11" ARCH="32"
  - ACTION="ci/build_cmake.sh"     VERSION="cpp03" ARCH="64"
  - ACTION="ci/build_cmake.sh"     VERSION="cpp03" ARCH="32"

script:
  - git clean -xdf && ${ACTION} ${VERSION} ${ARCH}
